import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  reference: [
    {
      type: 'category',
      label: 'DynamoDB',
      items: [{ type: 'autogenerated', dirName: 'dynamo-db' }],
    },
    {
      type: 'category',
      label: 'Utils',
      items: [{ type: 'autogenerated', dirName: 'utils' }],
    },
  ],
};

export default sidebars;
